MAP: dict[str, list[str]] = {
    "cafeteria":      ["hallway_A", "hallway_F", "weapons"],
    "weapons":        ["cafeteria", "hallway_E"],
    "o2":             ["hallway_E"],
    "navigation":     ["hallway_E"],
    "shields":        ["hallway_E", "hallway_D"],
    "communications": ["hallway_D"],
    "storage":        ["hallway_D", "hallway_F", "hallway_C"],
    "admin":          ["hallway_F"],
    "electrical":     ["hallway_C"],
    "lower_engine":   ["hallway_C", "hallway_B"],
    "reactor":        ["hallway_B"],
    "security":       ["hallway_B"],
    "upper_engine":   ["hallway_A", "hallway_B"],
    "medbay":         ["hallway_A"],
    "hallway_A":      ["cafeteria", "upper_engine", "medbay"],
    "hallway_B":      ["upper_engine", "lower_engine", "reactor", "security"],
    "hallway_C":      ["storage", "electrical", "lower_engine"],
    "hallway_D":      ["shields", "communications", "storage"],
    "hallway_E":      ["weapons", "o2", "navigation", "shields"],
    "hallway_F":      ["cafeteria", "storage", "admin"],
}

VENT_NETWORKS: dict[int, list[str]] = {
    1: ["cafeteria", "admin", "hallway_E"],
    2: ["security", "medbay", "electrical"],
    3: ["weapons", "navigation", "shields"],
    4: ["lower_engine", "upper_engine", "reactor"],
}

TASKS: list[dict] = [
    {"id": "swipe_card",            "name": "Swipe Card",            "type": "common", "location": "admin",          "turns": 1},
    {"id": "fix_wiring_electrical", "name": "Fix Wiring",            "type": "common", "location": "electrical",     "turns": 1},
    {"id": "fix_wiring_hallway_a",  "name": "Fix Wiring",            "type": "common", "location": "hallway_A",      "turns": 1},
    {"id": "fix_wiring_security",   "name": "Fix Wiring",            "type": "common", "location": "security",       "turns": 1},

    {"id": "reboot_panel",          "name": "Reboot Panel",          "type": "short",  "location": "cafeteria",      "turns": 1},
    {"id": "calibrate_distributor", "name": "Calibrate Distributor", "type": "short",  "location": "electrical",     "turns": 2},
    {"id": "chart_course",          "name": "Chart Course",          "type": "short",  "location": "navigation",     "turns": 1},
    {"id": "clean_o2_filter",       "name": "Clean O2 Filter",       "type": "short",  "location": "o2",             "turns": 1},
    {"id": "prime_shields",         "name": "Prime Shields",         "type": "short",  "location": "shields",        "turns": 1},
    {"id": "stabilize_steering",    "name": "Stabilize Steering",    "type": "short",  "location": "navigation",     "turns": 1},
    {"id": "unlock_manifolds",      "name": "Unlock Manifolds",      "type": "short",  "location": "reactor",        "turns": 2},
    {"id": "start_reactor",         "name": "Start Reactor",         "type": "short",  "location": "reactor",        "turns": 2},
    {"id": "clear_asteroids",       "name": "Clear Asteroids",       "type": "short",  "location": "weapons",        "turns": 2},
    {"id": "submit_scan",           "name": "Submit Scan",           "type": "short",  "location": "medbay",         "turns": 2},
    {"id": "inspect_sample",        "name": "Inspect Sample",        "type": "short",  "location": "medbay",         "turns": 2},
    {"id": "accept_power_upper",    "name": "Accept Power",          "type": "short",  "location": "upper_engine",   "turns": 1},
    {"id": "accept_power_lower",    "name": "Accept Power",          "type": "short",  "location": "lower_engine",   "turns": 1},
    {"id": "accept_power_comms",    "name": "Accept Power",          "type": "short",  "location": "communications", "turns": 1},
    {"id": "accept_power_security", "name": "Accept Power",          "type": "short",  "location": "security",       "turns": 1},
    {"id": "accept_power_shields",  "name": "Accept Power",          "type": "short",  "location": "shields",        "turns": 1},
    {"id": "accept_power_weapons",  "name": "Accept Power",          "type": "short",  "location": "weapons",        "turns": 1},
    {"id": "accept_power_o2",       "name": "Accept Power",          "type": "short",  "location": "o2",             "turns": 1},
    {"id": "refuel_tank",           "name": "Refuel Tank",           "type": "short",  "location": "storage",        "turns": 1},
    {"id": "log_entry",             "name": "Log Entry",             "type": "short",  "location": "admin",          "turns": 1},
    {"id": "align_engine_upper",    "name": "Align Engine",          "type": "short",  "location": "upper_engine",   "turns": 1},
    {"id": "align_engine_lower",    "name": "Align Engine",          "type": "short",  "location": "lower_engine",   "turns": 1},
    {"id": "scan_comms_array",      "name": "Scan Comms Array",      "type": "short",  "location": "communications", "turns": 1},
    {"id": "vent_check",            "name": "Vent Check",            "type": "short",  "location": "hallway_B",      "turns": 1},
    {"id": "tighten_bolts",         "name": "Tighten Bolts",         "type": "short",  "location": "hallway_C",      "turns": 1},
]

ROSTER: list[dict] = [
    {"color": "red",    "model": "anthropic/claude-sonnet-4-6"},
    {"color": "blue",   "model": "openai/gpt-4o"},
    {"color": "green",  "model": "google/gemini-2.5-flash"},
    {"color": "orange", "model": "deepseek/deepseek-v4-flash"},
    {"color": "purple", "model": "x-ai/grok-4.3"},
    {"color": "yellow", "model": "qwen/qwen3.7-plus"},
    {"color": "pink",   "model": "minimax/minimax-m3"},
    {"color": "teal",   "model": "nvidia/nemotron-3-super"},
]

NODE_POSITIONS: dict[str, tuple[int, int]] = {
    "cafeteria":      (800, 500),
    "weapons":        (1050, 300),
    "o2":             (1050, 150),
    "navigation":     (900, 100),
    "shields":        (700, 150),
    "communications": (550, 150),
    "storage":        (500, 300),
    "admin":          (650, 450),
    "electrical":     (350, 300),
    "lower_engine":   (350, 500),
    "reactor":        (200, 500),
    "security":       (200, 650),
    "upper_engine":   (500, 650),
    "medbay":         (650, 650),
    "hallway_A":      (700, 600),
    "hallway_B":      (350, 600),
    "hallway_C":      (350, 400),
    "hallway_D":      (600, 250),
    "hallway_E":      (900, 250),
    "hallway_F":      (600, 380),
}
