"""All system prompt templates."""

CREWMATE_SYSTEM_PROMPT = ""
IMPOSTOR_SYSTEM_PROMPT = ""
GHOST_SYSTEM_PROMPT = ""
MEETING_SCRATCHPAD_PROMPT = ""
MEETING_REBUTTAL_PROMPT = ""
MEETING_VOTE_PROMPT = ""
